[package]
name = "salt-compressor"
version = "0.4.0"
authors = ["Alexander Thaller <alexander.thaller@trivago.com>"]

[dependencies]
colored = "1"
log = "0.3"
loggerv = "0.3"
regex = "0.2"
serde_json = "1"
time = "0.1"

[dependencies.clap]
version = "2"
features = ["yaml"]
